### ISSUE TITLE
can you give steps on how run notability2pdf.py

### ISSUE THREAD

**Issue by supermangithu** [steventango/notability2pdf#1]
I'm new to python.I just basicly know how to run .py script,not working well.Can you give steps on how run notability2pdf.py well,thanks in advance!
Here below is debug information.
Traceback (most recent call last):
  File "C:\run\notability2pdf.py", line 27, in <module>
    pdfs = os.listdir(pdf_folder_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified:

**Comment by steventango** [comment]
Hi thanks, I believe you likely ran the script properly, but the notability file you have doesn't have a PDF in it, thanks for catching this. I'll fix the script so it doesn't raise an error for this case. If you don't mind, can you send the file here? Note, because this is Github the file would be made public.
